# Generated by Django 2.2.1 on 2019-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokeson', '0004_auto_20190916_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pricture',
            field=models.ImageField(default='boke/static/images/01.jpg', upload_to='images'),
        ),
    ]
