# Generated by Django 2.2.1 on 2019-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokeson', '0005_auto_20190916_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click',
            field=models.ImageField(default=0, upload_to='', verbose_name='点击率'),
        ),
        migrations.AddField(
            model_name='article',
            name='recommend',
            field=models.ImageField(default=0, upload_to='', verbose_name='推荐'),
        ),
    ]
