# Generated by Django 2.2.1 on 2019-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='stell',
            field=models.IntegerField(default=10),
        ),
    ]
